{
 "title": "ipo",
 "time": { "from": "2020-12-31T16:00:00.000Z", "to": "now" },
 "refresh": "2h",
 "panels": [
  {
   "title": "各交易所截止本日总量",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  TO_TIMESTAMP(\"time\" / 1000)::DATE AS time,\n  \"issue_market_desc\",\n  \"business_type_desc\",\n  \"stock_exchange_desc\",\n  MAX(\"count\") as count,\n  CONCAT_WS('-', \"stock_exchange_desc\", \"issue_market_desc\", \"business_type_desc\") AS legend\nFROM \n  \"MARKET_COUNT\"\nGROUP BY \n  TO_TIMESTAMP(\"time\" / 1000)::DATE,\n  \"stock_exchange_desc\",\n  \"issue_market_desc\",\n  \"business_type_desc\"\nORDER BY \n  \"time\",\n  \"stock_exchange_desc\",\n  \"issue_market_desc\",\n  \"business_type_desc\"\n"
    }
   ]
  },
  {
   "title": "各交易所按天总量",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT \n  TO_TIMESTAMP(\"time\" / 1000)::DATE AS time,\n  \"issue_market_desc\",\n  \"business_type_desc\",\n  \"stock_exchange_desc\",\n  MAX(\"count\") as count,\n  CONCAT_WS('-', \"stock_exchange_desc\", \"issue_market_desc\", \"business_type_desc\") AS legend\nFROM \n  \"MARKET_COUNT\"\nWHERE \n  \"issue_market_desc\" NOT IN ('沪市主板', '深市主板')\n  and count > 0\nGROUP BY \n  TO_TIMESTAMP(\"time\" / 1000)::DATE,\n  \"stock_exchange_desc\",\n  \"issue_market_desc\",\n  \"business_type_desc\"\nORDER BY \n  \"time\",\n  \"stock_exchange_desc\",\n  \"issue_market_desc\",\n  \"business_type_desc\""
    }
   ]
  },
  {
   "title": "科创板本年度提交IPO",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(total_fund_rasing) as \"提交IPO公司数量\"\nFROM \"SH_IPO\"\nwhere (create_time / 1000) > $__unixEpochFrom()\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  sum(total_fund_rasing) as \"提交IPO公司募资资金\"\nFROM \"SH_IPO\"\nwhere (create_time / 1000) > $__unixEpochFrom()\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  sum(total_fund_rasing) as \"IPO成功募资资金\"\nFROM \"SH_IPO\"\nwhere (create_time / 1000) > $__unixEpochFrom()\nand stage = 5 and stage_status = 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  count(total_fund_rasing) as \"IPO成功公司数量\"\nFROM \"SH_IPO\"\nwhere (create_time / 1000) > $__unixEpochFrom()\nand stage = 5 and stage_status = 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  count(total_fund_rasing) as \"本年度IPO成功上市公司数量\"\nFROM \"SH_IPO\"\nwhere (update_time / 1000) > $__unixEpochFrom()\nand stage = 5 and stage_status = 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  sum(total_fund_rasing) as \"本年度IPO成功上市公司募资资金\"\nFROM \"SH_IPO\"\nwhere (update_time / 1000) > $__unixEpochFrom()\nand stage = 5 and stage_status = 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "科创板本年度提交IPO",
   "type": "piechart",
   "gridPos": { "h": 31, "w": 13, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  csrc_desc,\n  count(*)\nFROM \"SH_IPO\"\nwhere (create_time / 1000) > $__unixEpochFrom()\ngroup by csrc_desc"
    }
   ]
  },
  {
   "title": "科创板本年度提交IPO",
   "type": "bargauge",
   "gridPos": { "h": 31, "w": 11, "x": 13, "y": 35 },
   "targets": [
    {
     "rawSql": "SELECT\n  csrc_desc,\n  count(*)\nFROM \"SH_IPO\"\nwhere (create_time / 1000) > $__unixEpochFrom()\ngroup by csrc_desc\norder by count(*) desc"
    }
   ]
  },
  {
   "title": "科创板本年度成功上市IPO募资排名",
   "type": "bargauge",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 66 },
   "targets": [
    {
     "rawSql": "SELECT\n  total_fund_rasing,\n  company_name,\n  csrc_desc\nFROM \"SH_IPO\"\nwhere (update_time / 1000) > $__unixEpochFrom()\nand stage = 5 and stage_status = 1\norder by total_fund_rasing desc\n"
    }
   ]
  },
  {
   "title": "科创板本年度提交IPO募资排名",
   "type": "bargauge",
   "gridPos": { "h": 19, "w": 23, "x": 0, "y": 85 },
   "targets": [
    {
     "rawSql": "SELECT\n  total_fund_rasing,\n  company_name,\n  csrc_desc\nFROM \"SH_IPO\"\nwhere (create_time / 1000) > $__unixEpochFrom()\norder by total_fund_rasing desc"
    }
   ]
  },
  {
   "title": "创业板本年度提交IPO",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 23, "x": 0, "y": 104 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(total_fund_rasing) as \"提交IPO公司数量\"\nFROM \"SZ_IPO\"\nwhere (accept_apply_time / 1000) > $__unixEpochFrom()\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  sum(total_fund_rasing) as \"提交IPO公司募资资金\"\nFROM \"SZ_IPO\"\nwhere (accept_apply_time / 1000) > $__unixEpochFrom()\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  sum(total_fund_rasing) as \"IPO成功募资资金\"\nFROM \"SZ_IPO\"\nwhere (accept_apply_time / 1000) > $__unixEpochFrom()\nand stage = 40 and stage_status = 70\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  count(total_fund_rasing) as \"IPO成功公司数量\"\nFROM \"SZ_IPO\"\nwhere (accept_apply_time / 1000) > $__unixEpochFrom()\nand stage = 40 and stage_status = 70\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  count(total_fund_rasing) as \"本年度IPO成功上市公司数量\"\nFROM \"SZ_IPO\"\nwhere (accept_apply_time / 1000) > $__unixEpochFrom()\nand stage = 40 and stage_status = 70\nORDER BY 1"
    }
   ]
  },
  {
   "title": "创业板本年度提交IPO",
   "type": "piechart",
   "gridPos": { "h": 33, "w": 12, "x": 0, "y": 117 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  csrc_desc,\n  count(*)\nFROM \"SZ_IPO\"\nwhere (accept_apply_time / 1000) > $__unixEpochFrom()\ngroup by csrc_desc"
    }
   ]
  },
  {
   "title": "创业板本年度提交IPO",
   "type": "bargauge",
   "gridPos": { "h": 33, "w": 11, "x": 12, "y": 117 },
   "targets": [
    {
     "rawSql": "SELECT\n  csrc_desc,\n  count(*)\nFROM \"SZ_IPO\"\nwhere (accept_apply_time / 1000) > $__unixEpochFrom()\ngroup by csrc_desc\norder by count(*) desc"
    }
   ]
  },
  {
   "title": "创业板本年度成功IPO募资排名",
   "type": "bargauge",
   "gridPos": { "h": 19, "w": 23, "x": 0, "y": 150 },
   "targets": [
    {
     "rawSql": "SELECT\n  total_fund_rasing,\n  company_name,\n  csrc_desc\nFROM \"SZ_IPO\"\nwhere (update_time / 1000) > $__unixEpochFrom()\nand stage = 40 and stage_status = 70\norder by total_fund_rasing desc"
    }
   ]
  },
  {
   "title": "创业板本年度提交IPO募资排名",
   "type": "bargauge",
   "gridPos": { "h": 19, "w": 23, "x": 0, "y": 169 },
   "targets": [
    {
     "rawSql": "SELECT\n  total_fund_rasing,\n  company_name,\n  csrc_desc\nFROM \"SZ_IPO\"\nwhere (accept_apply_time / 1000) > $__unixEpochFrom()\norder by total_fund_rasing desc"
    }
   ]
  },
  {
   "title": "科创板本年度提交IPO",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 188 },
   "targets": [
    {
     "rawSql": "SELECT\n  create_time AS \"time\",\n  total_fund_rasing,\n  company_name as legend\nFROM \"SH_IPO\"\nwhere (create_time / 1000) > $__unixEpochFrom()\nORDER BY 1"
    }
   ]
  },
  {
   "title": "创业板本年度提交IPO",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 197 },
   "targets": [
    {
     "rawSql": "SELECT\n  accept_apply_time AS \"time\",\n  total_fund_rasing,\n  company_name as legend\nFROM \"SZ_IPO\"\nwhere (accept_apply_time / 1000) > $__unixEpochFrom()\nORDER BY 1"
    }
   ]
  },
  {
   "title": "科创板本年度更新IPO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 206 },
   "targets": [
    {
     "rawSql": "SELECT\n  update_time as time,\n  total_fund_rasing as \"value\",\n  company_name as legend\nFROM \"SH_IPO\"\nGROUP BY update_time, total_fund_rasing,legend\nORDER BY 1"
    }
   ]
  },
  {
   "title": "创业板板本年度更新IPO",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 214 },
   "targets": [
    {
     "rawSql": "SELECT\n  update_time AS \"time\",\n  total_fund_rasing,\n  company_name as legend\nFROM \"SZ_IPO\"\nORDER BY 1"
    }
   ]
  }
 ]
}