{
 "title": "再融资",
 "time": { "from": "2020-12-31T16:00:00.000Z", "to": "now" },
 "refresh": "2h",
 "panels": [
  {
   "title": "各交易所截止本日总量",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  TO_TIMESTAMP(\"time\" / 1000)::DATE AS time,\n  \"issue_market_desc\",\n  \"business_type_desc\",\n  \"stock_exchange_desc\",\n  MAX(\"count\") as count,\n  CONCAT_WS('-', \"stock_exchange_desc\", \"issue_market_desc\", \"business_type_desc\") AS legend\nFROM \n  \"MARKET_COUNT\"\nWHERE \nbusiness_type_desc = '再融资'\nGROUP BY \n  TO_TIMESTAMP(\"time\" / 1000)::DATE,\n  \"stock_exchange_desc\",\n  \"issue_market_desc\",\n  \"business_type_desc\"\nORDER BY \n  \"time\",\n  \"issue_market_desc\",\n  \"stock_exchange_desc\",\n  \"business_type_desc\"\n"
    }
   ]
  },
  {
   "title": "各交易所按天总量",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT \n  TO_TIMESTAMP(\"time\" / 1000)::DATE AS time,\n  \"issue_market_desc\",\n  \"business_type_desc\",\n  \"stock_exchange_desc\",\n  MAX(\"count\") as count,\n  CONCAT_WS('-', \"stock_exchange_desc\", \"issue_market_desc\", \"business_type_desc\") AS legend\nFROM \n  \"MARKET_COUNT\"\nWHERE \n  \"issue_market_desc\" NOT IN ('沪市主板', '深市主板')\n  and count > 0\n  and business_type_desc = '再融资'\nGROUP BY \n  TO_TIMESTAMP(\"time\" / 1000)::DATE,\n  \"stock_exchange_desc\",\n  \"issue_market_desc\",\n  \"business_type_desc\"\nORDER BY \n  \"time\",\n  \"stock_exchange_desc\",\n  \"issue_market_desc\",\n  \"business_type_desc\""
    }
   ]
  },
  {
   "title": "上交所本年度提交再融资",
   "type": "gauge",
   "gridPos": { "h": 19, "w": 11, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(total_fund_rasing) as \"提交再融资公司数量\"\nFROM \"SH_ZRZ\"\nwhere (accept_apply_time / 1000) > $__unixEpochFrom()\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  count(total_fund_rasing) as \"再融资成功公司数量\"\nFROM \"SH_ZRZ\"\nwhere (accept_apply_time / 1000) > $__unixEpochFrom()\nand stage = 4 or ( stage = 50 and stage_status = 1)\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  sum(total_fund_rasing) as \"提交再融资公司募资资金\"\nFROM \"SH_ZRZ\"\nwhere (accept_apply_time / 1000) > $__unixEpochFrom()\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  sum(total_fund_rasing) as \"再融资成功募资资金\"\nFROM \"SH_ZRZ\"\nwhere (accept_apply_time / 1000) > $__unixEpochFrom()\nand stage = 4 or ( stage = 50 and stage_status = 1)\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  count(total_fund_rasing) as \"本年度再融资成功上市公司数量\"\nFROM \"SH_ZRZ\"\nwhere (update_time / 1000) > $__unixEpochFrom()\nand stage = 4 or ( stage = 50 and stage_status = 1)\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  sum(total_fund_rasing) as \"本年度再融资成功上市公司募资资金\"\nFROM \"SH_ZRZ\"\nwhere (update_time / 1000) > $__unixEpochFrom()\nand stage = 4 or ( stage = 50 and stage_status = 1)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "深交所本年度提交再融资",
   "type": "gauge",
   "gridPos": { "h": 19, "w": 11, "x": 11, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(total_fund_rasing) as \"提交再融资公司数量\"\nFROM \"SZ_ZRZ\"\nwhere (accept_apply_time / 1000) > $__unixEpochFrom()\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  count(total_fund_rasing) as \"再融资成功公司数量\"\nFROM \"SZ_ZRZ\"\nwhere (accept_apply_time / 1000) > $__unixEpochFrom()\nand ( stage = 40 and stage_status = 70)\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  sum(total_fund_rasing) as \"提交再融资公司募资资金\"\nFROM \"SZ_ZRZ\"\nwhere (accept_apply_time / 1000) > $__unixEpochFrom()\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  sum(total_fund_rasing) as \"再融资成功募资资金\"\nFROM \"SZ_ZRZ\"\nwhere (accept_apply_time / 1000) > $__unixEpochFrom()\nand ( stage = 40 and stage_status = 70)\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  count(total_fund_rasing) as \"本年度再融资成功上市公司数量\"\nFROM \"SZ_ZRZ\"\nwhere (update_time / 1000) > $__unixEpochFrom()\nand ( stage = 40 and stage_status = 70)\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  sum(total_fund_rasing) as \"本年度再融资成功上市公司募资资金\"\nFROM \"SZ_ZRZ\"\nwhere (update_time / 1000) > $__unixEpochFrom()\nand ( stage = 40 and stage_status = 70)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "上交所本年度提交再融资",
   "type": "table",
   "gridPos": { "h": 31, "w": 11, "x": 0, "y": 37 },
   "targets": [
    {
     "rawSql": "SELECT\n  company_name,\n  total_fund_rasing,\n  accept_apply_date\nFROM \"SH_ZRZ\"\nwhere (accept_apply_time / 1000) > $__unixEpochFrom()\ngroup by company_name,total_fund_rasing,accept_apply_date\norder by total_fund_rasing desc"
    }
   ]
  },
  {
   "title": "深交所本年度提交再融资",
   "type": "table",
   "gridPos": { "h": 31, "w": 12, "x": 11, "y": 37 },
   "targets": [
    {
     "rawSql": "SELECT\n  company_name,\n  total_fund_rasing,\n  accept_apply_date\nFROM \"SZ_ZRZ\"\nwhere (accept_apply_time / 1000) > $__unixEpochFrom()\ngroup by company_name,total_fund_rasing,accept_apply_date\norder by total_fund_rasing desc"
    }
   ]
  },
  {
   "title": "上交所本年度提交再融资",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 68 },
   "targets": [
    {
     "rawSql": "SELECT\n  company_name,\n  total_fund_rasing,\n  accept_apply_time as \"time\"\nFROM \"SH_ZRZ\"\nwhere (accept_apply_time / 1000) > $__unixEpochFrom()\ngroup by company_name,total_fund_rasing,accept_apply_time\norder by accept_apply_time"
    }
   ]
  },
  {
   "title": "深交所本年度提交再融资",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 77 },
   "targets": [
    {
     "rawSql": "SELECT\n  company_name,\n  total_fund_rasing,\n  accept_apply_time as \"time\"\nFROM \"SZ_ZRZ\"\nwhere (accept_apply_time / 1000) > $__unixEpochFrom()\ngroup by company_name,total_fund_rasing,accept_apply_time\norder by accept_apply_time"
    }
   ]
  },
  {
   "title": "上交所本年度更新再融资",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 86 },
   "targets": [
    {
     "rawSql": "SELECT\n  company_name,\n  total_fund_rasing as value,\n  update_time as \"time\"\nFROM \"SH_ZRZ\"\nwhere (update_time / 1000) > $__unixEpochFrom()\ngroup by company_name,total_fund_rasing,update_time\norder by update_time"
    }
   ]
  },
  {
   "title": "创业板板本年度更新再融资",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 94 },
   "targets": [
    {
     "rawSql": "SELECT\n  company_name as legend,\n  total_fund_rasing,\n  update_time as \"time\"\nFROM \"SZ_ZRZ\"\nwhere (update_time / 1000) > $__unixEpochFrom()\ngroup by company_name,total_fund_rasing,update_time\norder by update_time"
    }
   ]
  }
 ]
}