{
 "title": "ipo",
 "time": { "from": "now/y", "to": "now" },
 "refresh": "2h",
 "panels": [
  {
   "title": "各交易所截止本日总量",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  stock_exchange_type_desc,\n  count\nFROM \"MARKET_COUNT\"\nORDER BY 1"
    }
   ]
  },
  {
   "title": "各交易所按天总量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  count,\n  stock_exchange_type_desc\nFROM \"MARKET_COUNT\"\nORDER BY 1"
    }
   ]
  },
  {
   "title": "科创板本年度提交IPO",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(total_fund_rasing) as \"提交IPO公司数量\"\nFROM \"KCB_IPO\"\nwhere (create_time / 1000) > $__unixEpochFrom()\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  sum(total_fund_rasing) as \"提交IPO公司募资资金\"\nFROM \"KCB_IPO\"\nwhere (create_time / 1000) > $__unixEpochFrom()\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  sum(total_fund_rasing) as \"IPO成功募资资金\"\nFROM \"KCB_IPO\"\nwhere (create_time / 1000) > $__unixEpochFrom()\nand stage = 5 and stage_status = 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  count(total_fund_rasing) as \"IPO成功公司数量\"\nFROM \"KCB_IPO\"\nwhere (create_time / 1000) > $__unixEpochFrom()\nand stage = 5 and stage_status = 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  count(total_fund_rasing) as \"本年度IPO成功上市公司数量\"\nFROM \"KCB_IPO\"\nwhere (update_time / 1000) > $__unixEpochFrom()\nand stage = 5 and stage_status = 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  sum(total_fund_rasing) as \"本年度IPO成功上市公司募资资金\"\nFROM \"KCB_IPO\"\nwhere (update_time / 1000) > $__unixEpochFrom()\nand stage = 5 and stage_status = 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "科创板本年度提交IPO",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 11, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  csrc_desc,\n  count(*)\nFROM \"KCB_IPO\"\nwhere (create_time / 1000) > $__unixEpochFrom()\ngroup by csrc_desc"
    }
   ]
  },
  {
   "title": "科创板本年度提交IPO",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  csrc_desc,\n  count(*)\nFROM \"KCB_IPO\"\nwhere (create_time / 1000) > $__unixEpochFrom()\ngroup by csrc_desc\norder by count(*) desc"
    }
   ]
  },
  {
   "title": "科创板本年度成功上市IPO募资排名",
   "type": "bargauge",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT\n  total_fund_rasing,\n  company_name,\n  csrc_desc\nFROM \"KCB_IPO\"\nwhere (update_time / 1000) > $__unixEpochFrom()\nand stage = 5 and stage_status = 1\norder by total_fund_rasing desc\n"
    }
   ]
  },
  {
   "title": "科创板本年度提交IPO募资排名",
   "type": "bargauge",
   "gridPos": { "h": 19, "w": 23, "x": 0, "y": 37 },
   "targets": [
    {
     "rawSql": "SELECT\n  total_fund_rasing,\n  company_name,\n  csrc_desc\nFROM \"KCB_IPO\"\nwhere (create_time / 1000) > $__unixEpochFrom()\norder by total_fund_rasing desc"
    }
   ]
  },
  {
   "title": "创业板本年度提交IPO",
   "type": "gauge",
   "gridPos": { "h": 15, "w": 8, "x": 0, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(total_fund_rasing) as \"提交IPO公司数量\"\nFROM \"CYB_IPO\"\nwhere (create_time / 1000) > $__unixEpochFrom()\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  sum(total_fund_rasing) as \"提交IPO公司募资资金\"\nFROM \"CYB_IPO\"\nwhere (create_time / 1000) > $__unixEpochFrom()\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  sum(total_fund_rasing) as \"IPO成功募资资金\"\nFROM \"CYB_IPO\"\nwhere (create_time / 1000) > $__unixEpochFrom()\nand stage = 40 and stage_status = 70\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  count(total_fund_rasing) as \"IPO成功公司数量\"\nFROM \"CYB_IPO\"\nwhere (create_time / 1000) > $__unixEpochFrom()\nand stage = 40 and stage_status = 70\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  count(total_fund_rasing) as \"本年度IPO成功上市公司数量\"\nFROM \"CYB_IPO\"\nwhere (update_time / 1000) > $__unixEpochFrom()\nand stage = 40 and stage_status = 70\nORDER BY 1"
    }
   ]
  },
  {
   "title": "创业板本年度提交IPO",
   "type": "piechart",
   "gridPos": { "h": 15, "w": 7, "x": 8, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  csrc_desc,\n  count(*)\nFROM \"CYB_IPO\"\nwhere (create_time / 1000) > $__unixEpochFrom()\ngroup by csrc_desc"
    }
   ]
  },
  {
   "title": "创业板本年度提交IPO",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 8, "x": 15, "y": 56 },
   "targets": [
    {
     "rawSql": "SELECT\n  csrc_desc,\n  count(*)\nFROM \"CYB_IPO\"\nwhere (create_time / 1000) > $__unixEpochFrom()\ngroup by csrc_desc\norder by count(*) desc"
    }
   ]
  },
  {
   "title": "创业板本年度成功IPO募资排名",
   "type": "bargauge",
   "gridPos": { "h": 19, "w": 23, "x": 0, "y": 71 },
   "targets": [
    {
     "rawSql": "SELECT\n  total_fund_rasing,\n  company_name,\n  csrc_desc\nFROM \"CYB_IPO\"\nwhere (update_time / 1000) > $__unixEpochFrom()\nand stage = 40 and stage_status = 70\norder by total_fund_rasing desc"
    }
   ]
  },
  {
   "title": "创业板本年度提交IPO募资排名",
   "type": "bargauge",
   "gridPos": { "h": 19, "w": 23, "x": 0, "y": 90 },
   "targets": [
    {
     "rawSql": "SELECT\n  total_fund_rasing,\n  company_name,\n  csrc_desc\nFROM \"CYB_IPO\"\nwhere (create_time / 1000) > $__unixEpochFrom()\norder by total_fund_rasing desc"
    }
   ]
  },
  {
   "title": "科创板本年度提交IPO",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 109 },
   "targets": [
    {
     "rawSql": "SELECT\n  create_time AS \"time\",\n  total_fund_rasing,\n  company_name\nFROM \"KCB_IPO\"\nORDER BY 1"
    }
   ]
  },
  {
   "title": "创业板本年度提交IPO",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 118 },
   "targets": [
    {
     "rawSql": "SELECT\n  create_time AS \"time\",\n  total_fund_rasing,\n  company_name\nFROM \"CYB_IPO\"\nORDER BY 1"
    }
   ]
  },
  {
   "title": "科创板本年度更新IPO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 127 },
   "targets": [
    {
     "rawSql": "SELECT\n  update_time as \"time\",\n  total_fund_rasing as \"value\"\nFROM \"KCB_IPO\"\nGROUP BY update_time, total_fund_rasing"
    }
   ]
  },
  {
   "title": "创业板板本年度更新IPO",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 135 },
   "targets": [
    {
     "rawSql": "SELECT\n  update_time AS \"time\",\n  total_fund_rasing,\n  company_name\nFROM \"CYB_IPO\"\nORDER BY 1"
    }
   ]
  }
 ]
}